package com.example.funkyeventapp.fragments;

import android.os.Bundle; import android.view.View; import android.widget.TextView; import android.widget.Toast;
import androidx.annotation.NonNull; import androidx.annotation.Nullable; import androidx.fragment.app.Fragment; import androidx.navigation.Navigation; import androidx.recyclerview.widget.LinearLayoutManager; import androidx.recyclerview.widget.RecyclerView;
import com.example.funkyeventapp.R; import com.example.funkyeventapp.adapters.CashboxTransactionAdapter; import com.example.funkyeventapp.models.Cashbox; import com.example.funkyeventapp.models.CashboxTransaction; import com.example.funkyeventapp.models.TransactionType; import com.example.funkyeventapp.repositories.MockDataRepository;
import java.math.BigDecimal; import java.text.DecimalFormat; import java.text.DecimalFormatSymbols; import java.util.List; import java.util.Locale;

public class CashboxFragment extends Fragment {
    private final MockDataRepository repository=MockDataRepository.getInstance();
    private final DecimalFormat money=new DecimalFormat("#,##0.00", DecimalFormatSymbols.getInstance(Locale.GERMANY));
    public CashboxFragment(){super(R.layout.fragment_cashbox);}
    @Override public void onViewCreated(@NonNull View view,@Nullable Bundle state){super.onViewCreated(view,state);Cashbox cashbox=repository.getCashboxForUser("user_teodora");if(cashbox==null){Toast.makeText(requireContext(),R.string.cashbox_not_found,Toast.LENGTH_SHORT).show();Navigation.findNavController(view).popBackStack();return;}List<CashboxTransaction> transactions=repository.getCashboxTransactions(cashbox.getId());BigDecimal received=repository.getCashboxTotal(cashbox.getId(),TransactionType.INCOME);BigDecimal spent=repository.getCashboxTotal(cashbox.getId(),TransactionType.EXPENSE);((TextView)view.findViewById(R.id.textCashboxOwner)).setText(getString(R.string.cashbox_owner,getString(R.string.user_name),cashbox.getDisplayCurrency().name()));((TextView)view.findViewById(R.id.textCashboxReceived)).setText(getString(R.string.received_value,money.format(received)));((TextView)view.findViewById(R.id.textCashboxSpent)).setText(getString(R.string.spent_value,money.format(spent)));((TextView)view.findViewById(R.id.textCashboxBalance)).setText(getString(R.string.balance_value,money.format(repository.getCashboxBalance(cashbox.getId()))));((TextView)view.findViewById(R.id.textCashboxEntriesTitle)).setText(getString(R.string.all_entries,transactions.size()));CashboxTransactionAdapter adapter=new CashboxTransactionAdapter(new CashboxTransactionAdapter.Listener(){public void onEdit(CashboxTransaction item){coming(view);}public void onDelete(CashboxTransaction item){coming(view);}});adapter.submitList(transactions);RecyclerView list=view.findViewById(R.id.recyclerCashbox);list.setLayoutManager(new LinearLayoutManager(requireContext()));list.setAdapter(adapter);view.findViewById(R.id.buttonCashboxBack).setOnClickListener(v->Navigation.findNavController(v).popBackStack());int[] actions={R.id.buttonCashboxAdd,R.id.buttonCashboxPdf,R.id.buttonCashboxCamera,R.id.buttonCashboxGallery};for(int id:actions)view.findViewById(id).setOnClickListener(this::coming);}
    private void coming(View view){String label=view.getContentDescription()!=null?view.getContentDescription().toString():view instanceof TextView?((TextView)view).getText().toString():getString(R.string.cashbox);Toast.makeText(requireContext(),getString(R.string.coming_later,label),Toast.LENGTH_SHORT).show();}
}
